# Generated by Django 3.0.5 on 2020-05-04 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockSchedularApp', '0003_auto_20200501_1725'),
    ]

    operations = [
     
    ]
