# Generated by Django 3.0.5 on 2020-05-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
