# Generated by Django 3.0.2 on 2020-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('subject', models.CharField(max_length=101)),
                ('year', models.IntegerField()),
                ('resourceType', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.IntegerField()),
                ('numberofUpvotes', models.IntegerField(default=0)),
                ('numberofDownvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=141)),
                ('title', models.CharField(max_length=101)),
                ('yearPlaced', models.IntegerField()),
                ('experience', models.CharField(blank=True, max_length=2000, null=True)),
                ('yearPassout', models.IntegerField()),
                ('numberofUpvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('EmailId', models.EmailField(max_length=100)),
                ('role', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('rollNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
