# Generated by Django 3.0.6 on 2020-05-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(default='student', max_length=10),
        ),
    ]
