# Generated by Django 3.0.6 on 2020-05-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0002_auto_20200516_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='company',
            field=models.CharField(default='', max_length=20),
        ),
    ]
