# Generated by Django 3.0.6 on 2020-05-18 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0003_interview_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsPYQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('commentBody', models.CharField(default='', max_length=1000)),
                ('pyq', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SCPapp.File')),
            ],
        ),
    ]
