# Generated by Django 3.0.6 on 2020-05-19 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0004_commentspyq'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentspyq',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
