# Generated by Django 3.0.6 on 2020-05-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0005_commentspyq_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentspyq',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
