# Generated by Django 3.0.6 on 2020-05-19 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0006_auto_20200519_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
