# Generated by Django 3.0.6 on 2020-05-19 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('SCPapp', '0008_auto_20200519_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentspyq',
            name='pyq',
        ),
        migrations.AddField(
            model_name='commentspyq',
            name='content_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='commentspyq',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
