# Generated by Django 3.0.6 on 2020-05-19 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0010_auto_20200519_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CommentsExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('commentBody', models.CharField(default='', max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exp', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SCPapp.Interview')),
            ],
        ),
    ]
