# Generated by Django 3.0.6 on 2020-05-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0011_auto_20200519_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='auther',
            field=models.CharField(default='Admin', max_length=141),
        ),
    ]
