# Generated by Django 3.0.6 on 2020-05-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0012_file_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='auther',
            new_name='author',
        ),
    ]
