# Generated by Django 3.0.6 on 2020-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0013_auto_20200519_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
