# Generated by Django 3.0.6 on 2020-05-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0014_file_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
