# Generated by Django 3.0.6 on 2020-05-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0015_interview_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created',
        ),
    ]
