# Generated by Django 3.0.6 on 2020-05-22 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0017_auto_20200522_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
