# Generated by Django 3.0.6 on 2020-05-22 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0018_interview_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsexp',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commentspyq',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='file',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
